name: nillion_aivm_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - pytorch
  - transformers
  - cryptography
  - pip:
    - nillion-aivm[examples]>=0.1.0
    - python-dotenv>=0.19.0
    - pytest>=7.0.0
    - faker>=8.0.0