name: nillion_aivm_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - transformers
  - cryptography
  - faker
  - pip:
    - aivm-client>=0.1.0
    - nillion-network-sdk>=0.1.0